% TIMEFORMAT='%3R'; { time (exec 2>&1; /Users/blanchette/misc/leo --foatp e --atp e="$E_HOME"/eprover --atp epclextract="$E_HOME"/epclextract --proofoutput 1 --timeout 30 /Users/blanchette/hgs/afp_mining/tools/judgment_day_2017/data_afp/leo2-mepo/BDD_General_data/prob_270__3183014_1 ) ; }
% This file was generated by Isabelle (most likely Sledgehammer)
% 2017-07-27 17:21:08.969

% Could-be-implicit typings (18)


thf(ty_n_t__Simpl____Heap__Oref, type,
    simpl_ref : $tType).


thf(ty_n_t__Nat__Onat, type,
    nat : $tType).

thf(ty_n_t__Int__Oint, type,
    int : $tType).

thf(sy_c_Fun_Ofun__upd_001t__Simpl____Heap__Oref_001t__Simpl____Heap__Oref, type,
    fun_up2047713087pl_ref : (simpl_ref > simpl_ref) > simpl_ref > simpl_ref > simpl_ref > simpl_ref).

thf(sy_c_If_001t__Simpl____Heap__Oref, type,
    if_Simpl_ref : $o > simpl_ref > simpl_ref > simpl_ref).













thf(fact_147_fun__upd__apply, axiom,
    ((fun_up2047713087pl_ref = (^[F2 : simpl_ref > simpl_ref]: (^[X4 : simpl_ref]: (^[Y4 : simpl_ref]: (^[Z3 : simpl_ref]: (if_Simpl_ref @ (Z3 = X4) @ Y4 @ (F2 @ Z3))))))))). % fun_upd_apply
thf(fact_149_fun__upd__upd, axiom,
    ((![F : simpl_ref > simpl_ref, X : simpl_ref, Y2 : simpl_ref, Z : simpl_ref]: ((fun_up2047713087pl_ref @ (fun_up2047713087pl_ref @ F @ X @ Y2) @ X @ Z) = (fun_up2047713087pl_ref @ F @ X @ Z))))). % fun_upd_upd
