% TIMEFORMAT='%3R'; { time (exec 2>&1; /Users/blanchette/.isabelle/contrib/e-2.0-2/x86_64-darwin/eprover --auto-schedule --tstp-in --tstp-out --silent --cpu-limit=2 --proof-object=1 /Users/blanchette/hgs/matryoshka/papers/2019-TACAS-ehoh/eval/judgment_day/judgment_day_lifting_512/fta/prob_628__4064848_1 ) ; }
% This file was generated by Isabelle (most likely Sledgehammer)
% 2018-05-22 18:50:52.732

% Could-be-implicit typings (8)

thf(ty_n_t__Polynomial__Opoly_Itf__a_J,type,poly_a : $tType).

thf(ty_n_t__Real__Oreal,type,real : $tType).

thf(ty_n_t__HOL__Obool,type,bool : $tType).

thf(ty_n_t__Nat__Onat,type,nat : $tType).

thf(ty_n_tf__a,type,a : $tType).

% Explicit typings (68)



thf(sy_c_Fundamental__Theorem__Algebra__Mirabelle__nbxpoepana_Oconstant_001tf__a_001tf__a,type,fundam1229340235nt_a_a : (a > a) > $o).




thf(sy_c_Fundamental__Theorem__Algebra__Mirabelle__nbxpoepana_Opsize_001tf__a,type,fundam1066354451size_a : poly_a > nat).


thf(sy_c_Groups_Oone__class_Oone_001t__Nat__Onat,type,one_one_nat : nat).





thf(sy_c_Groups_Oplus__class_Oplus_001t__Nat__Onat,type,plus_plus_nat : nat > nat > nat).






thf(sy_c_Groups_Oplus__class_Oplus_001t__Real__Oreal,type,plus_plus_real : real > real > real).


thf(sy_c_Groups_Oplus__class_Oplus_001tf__a,type,plus_plus_a : a > a > a).






thf(sy_c_Groups_Otimes__class_Otimes_001t__Real__Oreal,type,times_times_real : real > real > real).


thf(sy_c_Groups_Otimes__class_Otimes_001tf__a,type,times_times_a : a > a > a).


thf(sy_c_Groups_Ozero__class_Ozero_001t__Nat__Onat,type,zero_zero_nat : nat).





thf(sy_c_Groups_Ozero__class_Ozero_001t__Polynomial__Opoly_Itf__a_J,type,zero_zero_poly_a : poly_a).


thf(sy_c_Groups_Ozero__class_Ozero_001t__Real__Oreal,type,zero_zero_real : real).


thf(sy_c_Groups_Ozero__class_Ozero_001tf__a,type,zero_zero_a : a).


thf(sy_c_Nat_OSuc,type,suc : nat > nat).
thf(sy_c_Orderings_Oord__class_Oless_001t__Nat__Onat,type,ord_less_nat : nat > nat > bool).


thf(sy_c_Orderings_Oord__class_Oless_001t__Real__Oreal,type,ord_less_real : real > real > $o).




thf(sy_c_Polynomial_OpCons_001tf__a,type,pCons_a : a > poly_a > poly_a).





thf(sy_c_Polynomial_Opoly_001tf__a,type,poly_a2 : poly_a > a > a).








thf(sy_c_Power_Opower__class_Opower_001tf__a,type,power_power_a : a > nat > a).




thf(sy_c_pp,type,pp : bool > $o).



thf(sy_v_c____,type,c : a).

thf(sy_v_cs____,type,cs : poly_a).



thf(sy_v_p,type,p : poly_a).



% Relevant facts (608)


thf(fact_0_nc,axiom,((~ ((fundam1229340235nt_a_a @ (poly_a2 @ p)))))). % nc
thf(fact_1__092_060open_062_092_060not_062_A_I_092_060forall_062z_O_Az_A_092_060noteq_062_A_I0_058_058_Ha_J_A_092_060longrightarrow_062_Apoly_Acs_Az_A_061_A_I0_058_058_Ha_J_J_092_060close_062,axiom,((~ ((![Z : a]: ((~ ((Z = zero_zero_a))) => ((poly_a2 @ cs @ Z) = zero_zero_a))))))). % \<open>\<not> (\<forall>z. z \<noteq> (0::'a) \<longrightarrow> poly cs z = (0::'a))\<close>
thf(fact_29_sum__squares__eq__zero__iff,axiom,((![X2 : real, Y : real]: (((plus_plus_real @ (times_times_real @ X2 @ X2) @ (times_times_real @ Y @ Y)) = zero_zero_real) <=> ((X2 = zero_zero_real) & (Y = zero_zero_real)))))). % sum_squares_eq_zero_iff
thf(fact_30_add__less__same__cancel1,axiom,((![B : nat, A2 : nat]: ((pp @ (ord_less_nat @ (plus_plus_nat @ B @ A2) @ B)) <=> (pp @ (ord_less_nat @ A2 @ zero_zero_nat)))))). % add_less_same_cancel1
thf(fact_31_add__less__same__cancel1,axiom,((![B : real, A2 : real]: ((ord_less_real @ (plus_plus_real @ B @ A2) @ B) <=> (ord_less_real @ A2 @ zero_zero_real))))). % add_less_same_cancel1
thf(fact_32_add__less__same__cancel2,axiom,((![A2 : nat, B : nat]: ((pp @ (ord_less_nat @ (plus_plus_nat @ A2 @ B) @ B)) <=> (pp @ (ord_less_nat @ A2 @ zero_zero_nat)))))). % add_less_same_cancel2
thf(fact_33_add__less__same__cancel2,axiom,((![A2 : real, B : real]: ((ord_less_real @ (plus_plus_real @ A2 @ B) @ B) <=> (ord_less_real @ A2 @ zero_zero_real))))). % add_less_same_cancel2
thf(fact_34_less__add__same__cancel1,axiom,((![A2 : nat, B : nat]: ((pp @ (ord_less_nat @ A2 @ (plus_plus_nat @ A2 @ B))) <=> (pp @ (ord_less_nat @ zero_zero_nat @ B)))))). % less_add_same_cancel1
thf(fact_35_less__add__same__cancel1,axiom,((![A2 : real, B : real]: ((ord_less_real @ A2 @ (plus_plus_real @ A2 @ B)) <=> (ord_less_real @ zero_zero_real @ B))))). % less_add_same_cancel1
thf(fact_36_less__add__same__cancel2,axiom,((![A2 : nat, B : nat]: ((pp @ (ord_less_nat @ A2 @ (plus_plus_nat @ B @ A2))) <=> (pp @ (ord_less_nat @ zero_zero_nat @ B)))))). % less_add_same_cancel2

thf(fact_48_pCons__eq__iff,axiom,((![A2 : a, P : poly_a, B : a, Q2 : poly_a]: (((pCons_a @ A2 @ P) = (pCons_a @ B @ Q2)) <=> ((A2 = B) & (P = Q2)))))). % pCons_eq_iff
thf(fact_53_zero__eq__add__iff__both__eq__0,axiom,((![X2 : nat, Y : nat]: ((zero_zero_nat = (plus_plus_nat @ X2 @ Y)) <=> ((X2 = zero_zero_nat) & (Y = zero_zero_nat)))))). % zero_eq_add_iff_both_eq_0
thf(fact_123_pCons__0__0,axiom,(((pCons_a @ zero_zero_a @ zero_zero_poly_a) = zero_zero_poly_a))). % pCons_0_0
thf(fact_130_poly__0,axiom,((![X2 : a]: ((poly_a2 @ zero_zero_poly_a @ X2) = zero_zero_a)))). % poly_0
thf(fact_202_n__not__Suc__n,axiom,((![N : nat]: (~ ((N = (suc @ N))))))). % n_not_Suc_n
thf(fact_399_pCons_Oprems,axiom,((~ ((fundam1229340235nt_a_a @ (poly_a2 @ (pCons_a @ c @ cs))))))). % pCons.prems
thf(fact_400_pCons_Ohyps_I2_J,axiom,(((~ ((fundam1229340235nt_a_a @ (poly_a2 @ cs)))) => (?[K : nat, A : a, Q : poly_a]: ((~ ((A = zero_zero_a))) & ((~ ((K = zero_zero_nat))) & (((plus_plus_nat @ (plus_plus_nat @ (fundam1066354451size_a @ Q) @ K) @ one_one_nat) = (fundam1066354451size_a @ cs)) & (![Z2 : a]: ((poly_a2 @ cs @ Z2) = (plus_plus_a @ (poly_a2 @ cs @ zero_zero_a) @ (times_times_a @ (power_power_a @ Z2 @ K) @ (poly_a2 @ (pCons_a @ A @ Q) @ Z2)))))))))))). % pCons.hyps(2)
thf(fact_590_One__nat__def,axiom,((one_one_nat = (suc @ zero_zero_nat)))). % One_nat_def
thf(fact_592_plus__1__eq__Suc,axiom,(((plus_plus_nat @ one_one_nat) = suc))). % plus_1_eq_Suc
