%------------------------------------------------------------------------------
% File     : PHI004^4 : TPTP v7.2.0. Released v6.4.0.
% Domain   : Philosophy
% Problem  : Being God-like is an essence of any God-like being
% Version  : [Ben16] axioms : Biased.
% English  :

% Refs     : [Ben16] Benzmueller (2016), Email to Geoff Sutcliffe
% Source   : [Ben16]
% Names    : Sledgehammer_T2_S5U_direct_satallax.p [Ben16]

% Status   : Theorem
% Rating   : 0.78 v7.2.0, 0.75 v7.0.0, 0.71 v6.4.0
% Syntax   : Number of formulae    :   17 (   0 unit;   6 type;   0 defn)
%            Number of atoms       :   81 (   3 equality;  57 variable)
%            Maximal formula depth :   13 (   7 average)
%            Number of connectives :   69 (   5   ~;   1   |;   2   &;  52   @)
%                                         (   0 <=>;   9  =>;   0  <=;   0 <~>)
%                                         (   0  ~|;   0  ~&)
%            Number of type conns  :   31 (  31   >;   0   *;   0   +;   0  <<)
%            Number of symbols     :    8 (   6   :;   0   =)
%            Number of variables   :   37 (   1 sgn;  24   !;   2   ?;  11   ^)
%                                         (  37   :;   0  !>;   0  ?*)
%                                         (   0  @-;   0  @+)
% SPC      : TH0_THM_EQU_NAR

% Comments : This problem file has been generated by Sledgehammer (satallax
%            translation) in default setting.
%------------------------------------------------------------------------------
%----Could-be-implicit typings (2)
thf(ty_n_t__QML____S5U__O__092__060mu__062, type,
    qML_mu : $tType).
thf(ty_n_t__QML____S5U__Oi, type,
    qML_i : $tType).

%----Explicit typings (4)
thf(sy_c_Scott__S5U_OG, type,
    scott_G : qML_mu > qML_i > $o).

%----Relevant facts (10)
thf(fact_0_G__def, axiom,
    (
        (scott_G =
         (^[X : qML_mu]:
          (^[W : qML_i]:
           (![Y : qML_mu > qML_i > $o]:
            (Y @ X @ W))))))). % G_def
